"""empty message

Revision ID: 6bb54532cc49
Revises: fbcaaabb55b7
Create Date: 2025-12-05 16:42:38.171494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb54532cc49'
down_revision = 'fbcaaabb55b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_link', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('community_link')

    # ### end Alembic commands ###
