"""empty message

Revision ID: c9add44d9a32
Revises: 
Create Date: 2025-11-18 02:05:36.812400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9add44d9a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_email', sa.String(length=100), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super', 'moderator'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('career',
    sa.Column('career_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('career_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('demand_level', sa.Enum('High', 'Medium', 'Low'), nullable=False),
    sa.Column('average_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('career_id'),
    sa.UniqueConstraint('career_name')
    )
    op.create_table('education_level',
    sa.Column('edulevel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edulevel_name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('edulevel_id')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('Technical', 'Soft', 'Other'), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('education_level', sa.Enum('Secondary', 'Diploma', 'BSc', 'MSc', 'PhD'), nullable=True),
    sa.Column('career_goal', sa.String(length=100), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('current_level', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.String(length=255), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('career_recommendation',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('date_generated', sa.DateTime(), nullable=True),
    sa.Column('prof_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('career_skill',
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('career_id', 'skill_id')
    )
    op.create_table('professional',
    sa.Column('professional_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('linkedin_id', sa.String(length=100), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('professional_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.create_table('user_interest',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'career_id')
    )
    op.create_table('user_skill',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skill')
    op.drop_table('user_interest')
    op.drop_table('professional')
    op.drop_table('career_skill')
    op.drop_table('career_recommendation')
    op.drop_table('user')
    op.drop_table('skill')
    op.drop_table('education_level')
    op.drop_table('career')
    op.drop_table('admin')
    # ### end Alembic commands ###
