"""empty message

Revision ID: fbcaaabb55b7
Revises: ba2f215ced07
Create Date: 2025-12-04 18:25:46.508923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcaaabb55b7'
down_revision = 'ba2f215ced07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('community_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id'),
    sa.UniqueConstraint('community_name')
    )
    op.create_table('user_community',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_community')
    op.drop_table('community')
    # ### end Alembic commands ###
